CREATE TABLE PLAYER(
	nickname VARCHAR(20) PRIMARY KEY
)

CREATE TABLE SCORE(
	idScore SERIAL PRIMARY KEY,
	score INT NOT NULL,
	nickname VARCHAR(20) NOT NULL
)

ALTER TABLE SCORE
ADD CONSTRAINT fk_player_score
FOREIGN KEY (nickname) REFERENCES PLAYER(nickname);